//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exploreh.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedorContato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public int FornecedorId { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
