//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exploreh.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilTela
    {
        public int Perfil_Id { get; set; }
        public int Tela_Id { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int Id { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Tela Tela { get; set; }
    }
}
