//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exploreh.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBairro
    {
        public int IdBairro { get; set; }
        public Nullable<int> IdCidade { get; set; }
        public string DcrChaveLocalidade { get; set; }
        public string DcrChaveBairro { get; set; }
        public string DcrNome { get; set; }
        public string AbrevNome { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public string EstReg { get; set; }
    }
}
