//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exploreh.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCidade()
        {
            this.ClienteEndereco = new HashSet<ClienteEndereco>();
            this.FornecedorEndereco = new HashSet<FornecedorEndereco>();
        }
    
        public int IdCidade { get; set; }
        public Nullable<int> IdUnidadeFederacao { get; set; }
        public string DcrSiglaPais { get; set; }
        public string DcrSiglaUf { get; set; }
        public string DcrChaveLocalidade { get; set; }
        public string DcrNome { get; set; }
        public string DcrCep { get; set; }
        public string AbrevNome { get; set; }
        public string TipLocalidade { get; set; }
        public string SituacaoLocalidade { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public string EstReg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteEndereco> ClienteEndereco { get; set; }
        public virtual TblUnidadeFederacao TblUnidadeFederacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedorEndereco> FornecedorEndereco { get; set; }
    }
}
