//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exploreh.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogradouro
    {
        public int IdLogradouro { get; set; }
        public Nullable<int> IdBairro { get; set; }
        public string DcrChaveBairroInicial { get; set; }
        public string DcrChaveBairroFinal { get; set; }
        public string DcrTipoLogradouro { get; set; }
        public string DcrPreposicao { get; set; }
        public string DcrTituloPatente { get; set; }
        public string DcrChaveLogradouro { get; set; }
        public string DcrNome { get; set; }
        public string AbrevNome { get; set; }
        public string DcrCep { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public string EstReg { get; set; }
    }
}
